name: Our Artifacts 2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  up:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, Github Action!" > hello.txt
      - uses: actions/upload-artifact@v3
        with:
          name: hello
          path: hello.txt
          
  down:
    runs-on: ubuntu-latest
    needs: up
    steps:
      - run: cat hello.txt
        continue-on-error: true
      - uses: actions/download-artifact@v3
        with:
          name: hello
      - run: cat hello.txt